### ISSUE TITLE
Unexpected rendering of values in locode screen...

### ISSUE THREAD

**Issue by jsobell** [ServiceStack/locode#1]
Just running through a test with locode on an existing database against SQL Server.
On some tables when there is an integer identifier ID field the forms display a different field's value.
Is this an attempt to make ID numbers more meaningful by showing the first text field in the dataset? If so, how is this configurable (or how is it disabled)?

![Screenshot 2023-02-20 101605](https://user-images.githubusercontent.com/834155/219981347-513e7e8a-ced7-4760-a162-27b1195cb53f.png)

**Comment by mythz** [comment]
It can be customized [using the [Ref] attribute](https://docs.servicestack.net/locode/programmatic#custom-ui-references) where it uses the `RefLabel` field.

Can you please use one of the [listed support options](https://docs.servicestack.net/#community-support) for future support q's, e.g. 
 - https://forums.servicestack.net
 - https://servicestack.net/ask (GitHub Discussions)
 - https://github.com/ServiceStack/issues
